#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────
# migrate-to-broker.sh — Migrate Clawdia v3 → Clawdia Framework Broker
#
# What this does:
#   1. Backs up current crontab to /root/clawdia-v3/backup/crontab.bak
#   2. Backs up current PM2 process list
#   3. Documents old cron → new scheduled task mapping
#   4. Removes the content-pipeline crontab entry (if any)
#   5. Stops (but does NOT delete) old agent-stack PM2 process
#   6. Builds the framework
#   7. Starts the new clawdia-broker PM2 process
#   8. Verifies dashboard (port 3000) and API (port 3001) are accessible
#   9. Sends Telegram notification
#
# Rollback: run scripts/rollback-to-trading.sh
#
# IMPORTANT: Run from /root/clawdia-framework
# ─────────────────────────────────────────────────────────

set -euo pipefail

FRAMEWORK_DIR="/root/clawdia-framework"
V3_DIR="/root/clawdia-v3"
BACKUP_DIR="${V3_DIR}/backup"
LOG_DIR="/var/log/clawdia"
STATE_DIR="/var/lib/clawdia"
DASHBOARD_PORT=3000
API_PORT=3001

# Colors
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
success() { echo -e "${GREEN}[OK]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
die()     { echo -e "${RED}[FATAL]${NC} $*"; exit 1; }

# ─────────────────────────────────────────────────────────
# Pre-flight checks
# ─────────────────────────────────────────────────────────
info "=== Clawdia Migration: v3 Trading Bot → Framework Broker ==="
info ""

[[ -d "$FRAMEWORK_DIR" ]] || die "Framework not found at $FRAMEWORK_DIR"
[[ -d "$V3_DIR" ]] || warn "clawdia-v3 not found at $V3_DIR — skipping backup"
command -v pm2 &>/dev/null || die "pm2 not found — install with: npm install -g pm2"
command -v pnpm &>/dev/null || die "pnpm not found"
command -v curl &>/dev/null || die "curl not found"

# ─────────────────────────────────────────────────────────
# Step 1: Backup crontab
# ─────────────────────────────────────────────────────────
info "Step 1: Backing up crontab..."
mkdir -p "$BACKUP_DIR"
crontab -l > "${BACKUP_DIR}/crontab.bak" 2>/dev/null || echo "# No crontab" > "${BACKUP_DIR}/crontab.bak"
success "Crontab backed up to ${BACKUP_DIR}/crontab.bak"

# ─────────────────────────────────────────────────────────
# Step 2: Backup PM2 process list
# ─────────────────────────────────────────────────────────
info "Step 2: Backing up PM2 process list..."
pm2 list --no-color > "${BACKUP_DIR}/pm2-list.bak" 2>/dev/null || true
pm2 save --no-color > "${BACKUP_DIR}/pm2-dump.log" 2>/dev/null || true
success "PM2 list backed up to ${BACKUP_DIR}/pm2-list.bak"

# ─────────────────────────────────────────────────────────
# Step 3: Document cron mapping
# ─────────────────────────────────────────────────────────
info "Step 3: Writing cron migration map..."
cat > "${BACKUP_DIR}/cron-migration-map.txt" << 'CRON_MAP'
CLAWDIA v3 → FRAMEWORK BROKER: Cron Migration Map
===================================================
Generated by migrate-to-broker.sh

OLD CRON (v3)                    NEW SCHEDULED TASK (Framework)
─────────────────────────────    ──────────────────────────────────────────
*/30 * * * *                     market-opportunity-scanner     (*/30 * * * *)
  Weather Trading                  Market Opportunity Scanner
  → Scans weather prediction       → Brokers scan across ALL categories
    markets                          via ContractEngine + trading-specialist

0 */2 * * *                      high-value-job-scanner         (0 */2 * * *)
  High Conviction Scanner          High Value Job Scanner
  → Finds high-score trades        → Processes external broker request queue
                                     + economy heartbeat

0 8,20 * * *                     intelligence-briefing          (0 8,20 * * *)
  Crypto News Scraper              Intelligence Briefing
  → CryptoPanic + NewsAPI          → research-specialist + data-analyst
    sentiment scraping               → assembled briefing via Telegram

0 10,16,22 * * *                 system-economy-health-check    (0 10,16,22 * * *)
  Portfolio Health Check           System & Economy Health Check
  → Balance, positions, P&L        → Framework health + contract stats
                                     + platform P&L + Telegram report

0 */4 * * *                      agent-fleet-health             (0 */4 * * *)
  System Health Check              Agent Fleet Health
  → State files, logs, disk        → Heartbeats all agents, marks offline,
                                     checks circuit breakers, utilization

0 14 * * *                       morning-briefing-leo           (0 14 * * *)
  Morning Briefing                 Morning Briefing for Leo
  → Daily overview for Leo         → Overnight results + economy stats
                                     + intelligence highlights + schedule

0 5 * * *                        nightly-performance-review     (0 5 * * *)
  Nightly Meta-Learning            Nightly Performance Review
  → Trades review, learnings,      → Agent performance (reputation delta),
    strategy audit                   quality scores, margin analysis,
                                     failure root causes → /var/log/clawdia/reviews/

0 2 * * 0                        weekly-backup-report           (0 2 * * 0)
  Digital Citadel Backup           Weekly Backup & Report
  → Weekly system backup           → Framework state backup +
                                     weekly report → /var/lib/clawdia/backups/

All tasks create real TaskContracts visible on dashboard: http://localhost:3000
CRON_MAP
success "Migration map written to ${BACKUP_DIR}/cron-migration-map.txt"

# ─────────────────────────────────────────────────────────
# Step 4: Remove content-pipeline crontab entry (if any)
# ─────────────────────────────────────────────────────────
info "Step 4: Cleaning content-pipeline from crontab..."
CURRENT_CRON=$(crontab -l 2>/dev/null || echo "")
if echo "$CURRENT_CRON" | grep -q "content-pipeline"; then
  echo "$CURRENT_CRON" | grep -v "content-pipeline" | crontab -
  success "Removed content-pipeline crontab entry"
else
  info "No content-pipeline entry found in crontab — nothing to remove"
fi

# ─────────────────────────────────────────────────────────
# Step 5: Stop (don't delete) old agent-stack PM2 process
# ─────────────────────────────────────────────────────────
info "Step 5: Stopping old agent-stack PM2 process (NOT deleting)..."
if pm2 list --no-color 2>/dev/null | grep -q "agent-stack"; then
  pm2 stop agent-stack --no-color || warn "Could not stop agent-stack (may already be stopped)"
  success "agent-stack stopped (run 'pm2 restart agent-stack' to restore)"
else
  info "No agent-stack PM2 process found — skipping"
fi

# ─────────────────────────────────────────────────────────
# Step 6: Create required directories
# ─────────────────────────────────────────────────────────
info "Step 6: Creating required directories..."
mkdir -p "$LOG_DIR" "$STATE_DIR" "${LOG_DIR}/reviews" "${STATE_DIR}/backups"
success "Directories created: $LOG_DIR, $STATE_DIR"

# ─────────────────────────────────────────────────────────
# Step 7: Build the framework
# ─────────────────────────────────────────────────────────
info "Step 7: Building Clawdia Framework..."
cd "$FRAMEWORK_DIR"
pnpm build 2>&1 | tail -20
success "Framework built successfully"

# ─────────────────────────────────────────────────────────
# Step 8: Load Telegram env vars from v3 config
# ─────────────────────────────────────────────────────────
info "Step 8: Loading Telegram configuration..."
TELEGRAM_ENV=""
for ENV_PATH in "${V3_DIR}/config/.env" "${V3_DIR}/.env" "/root/.env"; do
  if [[ -f "$ENV_PATH" ]]; then
    # Extract Telegram vars without sourcing (safer)
    TELEGRAM_BOT_TOKEN=$(grep -E "^TELEGRAM_BOT_TOKEN=" "$ENV_PATH" | cut -d= -f2- | tr -d '"' | tr -d "'" 2>/dev/null || echo "")
    TELEGRAM_CHAT_ID=$(grep -E "^TELEGRAM_CHAT_ID=" "$ENV_PATH" | cut -d= -f2- | tr -d '"' | tr -d "'" 2>/dev/null || echo "")
    if [[ -n "$TELEGRAM_BOT_TOKEN" ]]; then
      TELEGRAM_ENV="TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN},TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}"
      success "Telegram config loaded from $ENV_PATH"
      break
    fi
  fi
done

if [[ -z "$TELEGRAM_ENV" ]]; then
  warn "No Telegram credentials found — notifications will be disabled"
  warn "Set TELEGRAM_BOT_TOKEN and TELEGRAM_CHAT_ID in ecosystem.config.js manually"
fi

# ─────────────────────────────────────────────────────────
# Step 9: Start clawdia-broker PM2 process
# ─────────────────────────────────────────────────────────
info "Step 9: Starting clawdia-broker PM2 process..."

# Stop existing clawdia-broker if running
pm2 stop clawdia-broker --no-color 2>/dev/null || true
pm2 delete clawdia-broker --no-color 2>/dev/null || true

# Start with env vars from v3 config
if [[ -n "$TELEGRAM_ENV" ]]; then
  pm2 start "$FRAMEWORK_DIR/ecosystem.config.js" \
    --env production \
    --no-color 2>&1 | tail -10
  # Inject telegram vars
  pm2 set clawdia-broker:env:TELEGRAM_BOT_TOKEN "${TELEGRAM_BOT_TOKEN}" 2>/dev/null || true
  pm2 set clawdia-broker:env:TELEGRAM_CHAT_ID "${TELEGRAM_CHAT_ID}" 2>/dev/null || true
else
  pm2 start "$FRAMEWORK_DIR/ecosystem.config.js" --env production --no-color 2>&1 | tail -10
fi

success "clawdia-broker PM2 process started"

# Save PM2 state
pm2 save --no-color 2>/dev/null || true

# ─────────────────────────────────────────────────────────
# Step 10: Verify services are accessible
# ─────────────────────────────────────────────────────────
info "Step 10: Verifying services..."

# Wait for daemon to boot
sleep 5

# Check dashboard (port 3000)
if curl -sf --max-time 10 "http://localhost:${DASHBOARD_PORT}/" > /dev/null 2>&1; then
  success "Dashboard accessible at http://localhost:${DASHBOARD_PORT}/"
else
  warn "Dashboard not yet accessible at port ${DASHBOARD_PORT} (daemon may still be starting)"
  warn "Check: pm2 logs clawdia-broker"
fi

# Check API health (port 3001)
if curl -sf --max-time 10 "http://localhost:${API_PORT}/api/health" > /dev/null 2>&1; then
  success "REST API accessible at http://localhost:${API_PORT}/api/health"
else
  warn "REST API not yet accessible at port ${API_PORT} (daemon may still be starting)"
fi

# ─────────────────────────────────────────────────────────
# Step 11: Send Telegram notification
# ─────────────────────────────────────────────────────────
info "Step 11: Sending Telegram notification..."
if [[ -n "${TELEGRAM_BOT_TOKEN:-}" ]] && [[ -n "${TELEGRAM_CHAT_ID:-}" ]]; then
  MSG="🦅 Clawdia Broker is ONLINE. Migration complete.

Framework: Clawdia v3 Trading Bot → Framework Broker
Dashboard: http://localhost:${DASHBOARD_PORT}
API: http://localhost:${API_PORT}/api/broker

8 scheduled tasks loaded.
5 specialist agents registered.
State: /var/lib/clawdia/state.json
Logs: /var/log/clawdia/daemon.log"

  curl -s -X POST \
    "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
    -H "Content-Type: application/json" \
    -d "{\"chat_id\":\"${TELEGRAM_CHAT_ID}\",\"text\":\"${MSG}\"}" \
    > /dev/null 2>&1 && success "Telegram notification sent" || warn "Telegram notification failed"
else
  info "Skipping Telegram notification (no credentials)"
fi

# ─────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────
echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║         MIGRATION COMPLETE — CLAWDIA BROKER ONLINE       ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════╝${NC}"
echo ""
echo "  Dashboard:  http://localhost:${DASHBOARD_PORT}/"
echo "  REST API:   http://localhost:${API_PORT}/api/broker"
echo "  PM2 logs:   pm2 logs clawdia-broker"
echo "  Daemon log: tail -f ${LOG_DIR}/daemon.log"
echo ""
echo "  Old system: pm2 list (agent-stack is stopped, not deleted)"
echo "  Rollback:   bash ${FRAMEWORK_DIR}/scripts/rollback-to-trading.sh"
echo ""
